package fr.pacman.database.validation.core;

import java.util.HashMap;
import java.util.Map;

public class KeywordUtils {

	private static final String _postgres = "|ALL|ANALYSE|ANALYZE|AND|ANY|ARRAY|AS|ASC|ASYMETRIC|AUTHORIZATION|BINARY|BOTH|CASE|CAST|CHECK|COLLATE|COLUMN|"
			+ "CONCURRENTLY|CONSTRAINT|CREATE|CURRENT_SCHEMA|CURRENT_TIME|CURRENT_TIMESTAMP|CURRENT_USER|DEFAULT|DEFERRABLE|DESC|DISTINCT|DO|ELSE|END|EXCEPT|"
			+ "FALSE|FETCH|FOR|FOREIGN|FROM|FULL|GRANT|GROUP|HAVING|ILIKE|IN|INITIALLY|INNER|INTERSECT|INTO|IS|ISNULL|JOIN|LATERAL|LEADING|LEFT|LIKE|"
			+ "LOCALTIME|LOCALTIMESTAMP|NATURAL|NOT|NOTNULL|NULL|OFFSET|ON|ONLY|OR|ORDER|OUTER|OVERLAPS|PLACING|PRIMARY|REFERENCES|RETURNING|RIGHT|"
			+ "SELECT|SESSION_USER|SIMILAR|SOME|SYMETRIC|TABLE|TABLESAMPLE|THEN|TO|TRAILING|TRUE|UNION|UNIQUE|USER|USING|VARIADIC|VERBOSE|WHEN|"
			+ "WHERE|WINDOW|WITH|";

	private static final String _oracle = "|ACCESS|ADD|ALL|ALTER|AND|ANY|AS|ASC|AUDIT|BETWEEN|BY|CHAR|CHECK|CLUSTER|COLUMN-|COLUMN_|COMMENT|COMPRESS"
			+ "|CONNECT|CREATE|CURRENT|DATE|DECIMAL|DEFAULT|DELETE|DESC|DISTINCT|DROP|ELSE|EXCLUSIVE|EXISTS-|FILE|FLOAT|FOR|FROM|GRANT|GROUP|HAVING|"
			+ "IDENTIFIED|IMMEDIATE|IN|INCREMENT|INDEX|INITIALLY|INSERT|INTEGER|INTERSECT|INTO|IS|LEVEL|LIKE|LOCK|LONG|MAXEXTENTS|MINUS|MLSLABEL|"
			+ "MODE|MODIFY|NESTED_TABLE_ID (que sur attribut)|NOAUDIT|NOCOMPRESS|NOT|NOWAIT|NULL|NUMBER|OFF|ONLINE|OPTION|OR|ORDER|PCTFREE|PRIOR|"
			+ "PUBLIC|RAW|RENAME|RESOURCE|REVOKE|ROWID (au niveau colonne)|ROWNUM|ROWS|ROW-|SELECT|SESSION|SET|SHARE|SIZE|SMALLINT|START-|SUCCESSFUL|"
			+ "SYNONYM|SYSDATE|TABLE|THEN|TO|TRIGGER-|UID|UNION|UNIQUE|UPDATE|USER|VALIDATE|VALUES|VARCHAR|VARCHAR2|VIEW|WHENEVER|WHERE-|WITH|";

	private static final String _mysql = "|ACCESSIBLE|ADD|ALL|ALTER|ANALYZE|AND|AS|ASENSITIVE|BEFORE|BETWEEN|BIGINT|BINARY|BLOB|BODY|BOTH|BY|CALL|"
			+ "CASCADE|CASE|CHANGE|CHAR|CHECK|COLLATE|COLUMN|CONDITION|CONSTRAINT|CONTINUE|CREATE|CROSS|CURRENT_DATE|CURRENT_ROLE|CURRENT_TIME|"
			+ "CURRENT_TIMESTAMP|CURRENT_USER|CURSOR|DATABASE|DATABASES|DAY_MINUTE|DAY_SECOND|DEC|DECIMAL|DECLARE|DEFAULT|DELAYED|DELETE|"
			+ "DELETE_DOMAIN_ID|DESC|DESCRIBE|DETERMINISTIC|DISTINCT|DISTINCTROW|DIV|DO_DOMAIN_IDS|DOUBLE|DROP|DUAL|EACH|ELSE|ELSEIF|ELSIF|"
			+ "ENDCLOSED|ESCAPED|EXCEPT|EXISTS|EXIT|EXPLAIN|FALSE|FETCH|FLOAT|FOR|FORCE|FOREIGN|FROM|FULLTEXT|GENERAL|GOTO|GRANT|GROUP|"
			+ "HAVING|HIGH_PRIORITY|HISTORY|HOUR_MICROSECOND|HOUR_MINUTE|HOUR_SECOND|IF|IGNORE|IGNORE_DOMAIN_IDS|IGNORE_SERVER_IDS|IN|INDEX|"
			+ "INFILE|INNER|INOUT|INSENSITIVE|INT|INT1|INT2|INT3|INT4|INT8|INTEGER|INTERSECT|INTERVAL|INTO|IS|ITERATE|JOIN|KEY|KEYS|KILL|"
			+ "LEADING|LEAVE|LEFT|LIKE|LIMIT|LINEAR|LINES|LOAD|LOCALTIME|LOCALTIMESTAMP|LOCK|LONG|LONGBLOB|LONGTEXT|LOOP|LOW_PRIORITY|"
			+ "MASTER_HEARTBEAT_PERIOD|MASTER_SSL_VERIFY_SERVER_CERT|MATCH|MAXVALUE|MEDIUMBLOB|MEDIUMINT|MEDIUMTEXT|MIDDLEINT|MINUS|"
			+ "MINUTE_MICROSECOND|MINUTE_SECOND|MOD|MODIFIES|NATURAL|NOT|NOT_WRITE_TO_BINLOG|NULL|NUMERIC|OFFSET|ON|OPTIMIZE|OPTION|"
			+ "OPTIONALLY|OR|ORDER|OTHERS|OUT|OUTER|OUTFILE|OVER|PACKAGE|PAGE_CHECKSUM|PARSE_VCOL_EXPR|PARTITION|PERIOD|POSITION|PRECISION|"
			+ "PRIMARY|PROCEDURE|PURGE|RAISE|RANGE|READ|READS|READ_WRITE|REAL|RECURSIVE|REF_SYSTEM_ID|REFERENCES|REGEXP|RELEASE|REPEAT|"
			+ "REPLACE|REQUIRE|RESIGNAL|RESTRICT|RETURN|RETURNING|REVOKE|RIGHT|RLIKE|ROWNUM|ROWS|ROWTYPE|ROW_NUMBER|SCHEMA|SCHEMAS|"
			+ "SECOND_MICROSECOND|SELECT|SENSITIVE|SEPARATOR|SET|SHOW|SIGNAL|SLOW|SMALLINT|SPATIAL|SPECIFIC|SQL|SQLEXCEPTION|SQLSTATE|"
			+ "SQLWARNING|SQL_BIG_RESULT|SQL_CALC_FOUND_ROWS|SQL_SMALL_RESULT|SSL|STARTING|START-|STATS_AUTO_RECALC|STATS_PERSISTENT|"
			+ "STATS_SAMPLE_PAGES|STRAIGHT_JOIN|SYSDATE|SYSTEM|SYSTEM_TIME|TABLE|TERMINATED|THEN|TINYBLOB|TINYINT|TINYTEXT|TO|TRAILING|"
			+ "TRIGGER|TRUE|UNDO|UNIQUE|UNLOCK|UNSIGNED|USAGE|UPDATE|USE|USING|UTC_DATE|UTC_TIME|UTC_TIMESTAMP|VALUES|VARBINARY|VARCHAR|"
			+ "VARCHARACTER|VARYING|VERSIONING|WHEN|WHERE|WHILE|WINDOW|WITH|WITHOUT|WRITE|XOR|YEAR_MONTH|ZEROFILL|";

	private static final String _mariaDb = "|ACCESSIBLE|ADD|ALL|ALTER|ANALYZE|AND|AS|ASENSITIVE|BEFORE|BETWEEN|BIGINT|BINARY|BLOB|BODY|BOTH|BY|"
			+ "CALL|CASCADE|CASE|CHANGE|CHAR|CHECK|COLLATE|COLUMN|CONDITION|CONSTRAINT|CONTINUE|CREATE|CROSS|CURRENT_DATE|CURRENT_ROLE|"
			+ "CURRENT_TIME|CURRENT_TIMESTAMP|CURRENT_USER|CURSOR|DATABASE|DATABASES|DAY_MINUTE|DAY_SECOND|DEC|DECIMAL|DECLARE|DEFAULT|"
			+ "DELAYED|DELETE|DELETE_DOMAIN_ID|DESC|DESCRIBE|DETERMINISTIC|DISTINCT|DISTINCTROW|DIV|DO_DOMAIN_IDS|DOUBLE|DROP|DUAL|EACH|"
			+ "ELSE|ELSEIF|ELSIF|ENDCLOSED|ESCAPED|EXCEPT|EXISTS|EXIT|EXPLAIN|FALSE|FETCH|FLOAT|FOR|FORCE|FOREIGN|FROM|FULLTEXT|GENERAL|"
			+ "GOTO|GRANT|GROUP|HAVING|HIGH_PRIORITY|HISTORY|HOUR_MICROSECOND|HOUR_MINUTE|HOUR_SECOND|IF|IGNORE|IGNORE_DOMAIN_IDS|"
			+ "IGNORE_SERVER_IDS|IN|INDEX|INFILE|INNER|INOUT|INSENSITIVE|INT|INT1|INT2|INT3|INT4|INT8|INTEGER|INTERSECT|INTERVAL|"
			+ "INTO|IS|ITERATE|JOIN|KEY|KEYS|KILL|LEADING|LEAVE|LEFT|LIKE|LIMIT|LINEAR|LINES|LOAD|LOCALTIME|LOCALTIMESTAMP|LOCK|LONG|"
			+ "LONGBLOB|LONGTEXT|LOOP|LOW_PRIORITY|MASTER_HEARTBEAT_PERIOD|MASTER_SSL_VERIFY_SERVER_CERT|MATCH|MAXVALUE|MEDIUMBLOB|"
			+ "MEDIUMINT|MEDIUMTEXT|MIDDLEINT|MINUS|MINUTE_MICROSECOND|MINUTE_SECOND|MOD|MODIFIES|NATURAL|NOT|NOT_WRITE_TO_BINLOG|NULL|"
			+ "NUMERIC|OFFSET|ON|OPTIMIZE|OPTION|OPTIONALLY|OR|ORDER|OTHERS|OUT|OUTER|OUTFILE|OVER|PACKAGE|PAGE_CHECKSUM|PARSE_VCOL_EXPR|"
			+ "PARTITION|PERIOD|POSITION|PRECISION|PRIMARY|PROCEDURE|PURGE|RAISE|RANGE|READ|READS|READ_WRITE|REAL|RECURSIVE|REF_SYSTEM_ID|"
			+ "REFERENCES|REGEXP|RELEASE|REPEAT|REPLACE|REQUIRE|RESIGNAL|RESTRICT|RETURN|RETURNING|REVOKE|RIGHT|RLIKE|ROWNUM|ROWS|ROWTYPE|"
			+ "ROW_NUMBER|SCHEMA|SCHEMAS|SECOND_MICROSECOND|SELECT|SENSITIVE|SEPARATOR|SET|SHOW|SIGNAL|SLOW|SMALLINT|SPATIAL|SPECIFIC|SQL|"
			+ "SQLEXCEPTION|SQLSTATE|SQLWARNING|SQL_BIG_RESULT|SQL_CALC_FOUND_ROWS|SQL_SMALL_RESULT|SSL|STARTING|START-|STATS_AUTO_RECALC|"
			+ "STATS_PERSISTENT|STATS_SAMPLE_PAGES|STRAIGHT_JOIN|SYSDATE|SYSTEM|SYSTEM_TIME|TABLE|TERMINATED|THEN|TINYBLOB|TINYINT|TINYTEXT|"
			+ "TO|TRAILING|TRIGGER|TRUE|UNDO|UNIQUE|UNLOCK|UNSIGNED|USAGE|UPDATE|USE|USING|UTC_DATE|UTC_TIME|UTC_TIMESTAMP|VALUES|VARBINARY|"
			+ "VARCHAR|VARCHARACTER|VARYING|VERSIONING|WHEN|WHERE|WHILE|WINDOW|WITH|WITHOUT|WRITE|XOR|YEAR_MONTH|ZEROFILL|";

	private static final String _sqlServer = "|ADD|ALL|ALTER|AND|ANY|AS|ASC|AUTHORIZATION|BACKUP|BEGIN|BETWEEN|BREAK|BROWSE|BULK|BY|CASCADE|"
			+ "CASE|CHECK|CHECKPOINT|CLOSE|CLUSTERED|COALESCE|COLLATE|COLUMN|COMMIT|COMPUTE|CONSTRAINT|CONSTAINS|CONSTAINSTABLE|CONTINUE|CONVERT|"
			+ "CREATE|CROSS|CURRENT|CURRENT_DATE|CURRENT_TIME|CURRENT_TIMESTAMP|CURRENT_USER|CURSOR|DATABASE|DBCC|DEALLOCATE|DECLARE|DEFAULT|DENY|"
			+ "DESC|DISK|DISTINCT|DISTRIBUTED|DOUBLE|DROP|DUMP|ELSE|END|ERRLVL|ESCAPE|EXCEPT|EXEC|EXISTS|EXIT|EXTERNAL|FETCH|FILE|FILLFACTOR|FOR|"
			+ "FOREIGN|FREETEXT|FREETEXTTABLE|FROM|FULL|FUNCTION|GOTO|GRANT|GROUP|HAVING|HOLDLOCK|IDENTITY|IDENTITY_INSERT|IDENTITYCOL|IF|IN|INDEX|"
			+ "INNER|INSERT|INTERSECT|INTO|IS|JOIN|KEY|KILL|LEFT|LIKE|LINENO|LOAD|MERGE|NATIONAL|NOCHECK|NONCLUSTERED|NOT|NULL|NULLIF|OF|OFF|OFFSETS|"
			+ "OPEN|OPENDATASOURCE|OPENQUERY|OPENROWSET|OPTION|OR|ORDER|OUTER|OVER|PERCENT|PIVOT|PLAN|PRECISION|PRIMARY|PRINT|PROC|PROCEDURE|PUBLIC|"
			+ "RAISERROR|READ|READTEXT|RECONFIGURE|REFERENCES|REPLICATION|RESTORE|RESTRICT|RETURN|REVERT|REVOKE|RIGHT|ROLLBACK|ROWCOUNT|ROWGUIDCOL|"
			+ "RULE|SAVE|SCHEMA|SECURITYAUDIT|SELECT|SEMANTICKEYPHRASETABLE|SEMANTICSIMILARITYDETAILSTABLE|SEMANTICSIMILARITYTABLE|SESSION_USER|SET|"
			+ "SETUSER|SHUTDOWN|SOME|STATISTICS|TABLE|TABLESAMPLE|TEXTSIZE|THEN|TO|TRAN|TRANSACTION|TRIGGER|TRUNCATE|TRY_CONVERT|TSEQUAL|UNION|"
			+ "UNIQUE|UNPIVOT|UPDATE|UPDATETEXT|USE|USER|VALUES|VARYING|VIEW|WAITFOR|WHEN|WHERE|WHILE|WITH|WITH GROUP|WRITETEXT|";

	private static final String _h2 = "|ALL|AND|ANY|ARRAY|AS|ASYMETRIC|AUTHORIZATION|BETWEEN|BOTH|CASE|CAST|CHECK|CONSTRAINT|CROSS|CURRENT_CATALOG|"
			+ "CURRENT_DATE|CURRENT_PATH|CURRENT_ROLE|CURRENT_SCHEMA|CURRENT_TIME|CURRENT_TIMESTAMP|CURRENT_USER|DAY|DEFAULT|DISTINCT|ELSE|END|EXCEPT|"
			+ "EXISTS|FALSE|FETCH|FOR|FOREIGN|FROM|FULL|GROUP|GROUPS|HAVING|HOUR|IF|ILIKE|IN|INNER|INTERSECT|INTERVAL|IS|JOIN|KEY|LEADING|LEFT|LIKE|"
			+ "LIMIT|LOCALTIME|LOCALTIMESTAMP|MINUS|MINUTE|MONTH|NATURAL|NOT|NULL|OFFSET|ON|OR|ORDER|OVER|PARTITION|PRIMARY|QUALIFY|RANGE|REGEXP|"
			+ "RIGHT|ROW|ROWNUM|ROWS|SECOND|SELECT|SESSION_USER|SET|SOME|SYMMETRIC|SYSTEM_USER|TABLE|TO|TOP|TRAILING|TRUE|UESCAPE|UNION|UNIQUE|"
			+ "UNKNOW|USER|USING|VALUE|VALUES|WHEN|WHERE|WINDOW|WITH|YEAR_MONTH|_ROWID_|";

	// private static final String _logical = "";

	private static Map<String, String> _keywords;

	static {
		_keywords = new HashMap<>();
		_keywords.put("H2", _h2);
		_keywords.put("MARIADB", _mariaDb);
		_keywords.put("MYSQL", _mysql);
		_keywords.put("ORACLE", _oracle);
		_keywords.put("POSTGRES", _postgres);
		_keywords.put("SQLSERVER", _sqlServer);
	}

	/**
	 * 
	 * @param p_keyword
	 * @param p_dbType
	 * @return
	 */
	public static boolean is_reservedKeyword(final String p_keyword, final String p_dbType) {
		String reservedKeyword = _keywords.get(p_dbType.toUpperCase());
		if (null != reservedKeyword) {
			if (reservedKeyword.indexOf('|' + p_keyword.trim().toUpperCase() + '|') != -1) {
				return true;
			}
		}
		return false;
	}
}
